AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template to create an S3 bucket with versioning and encryption.

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "my-automated-s3-bucket"
      VersioningConfiguration:
        Status: "Enabled"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: "Environment"
          Value: "Production"
        - Key: "Project"
          Value: "S3Automation"

Outputs:
  BucketName:
    Description: "S3_Bucket"
    Value: !Ref S3Bucket
